# Generated by Django 4.1 on 2022-09-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id_check_in', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_llegada', models.DateField()),
                ('reserva_id_reserva', models.BigIntegerField(unique=True)),
                ('check_out_id_check_out', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'check_in',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id_check_out', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('check_in_id_check_in', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'check_out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ciudad', models.CharField(max_length=50)),
                ('region_id_region', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nom_comuna', models.CharField(max_length=50)),
                ('ciudad_id_ciudad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('cant_dormitorio', models.BigIntegerField()),
                ('cant_cama', models.BigIntegerField()),
                ('cant_banno', models.BigIntegerField()),
                ('cant_tv', models.BigIntegerField()),
                ('aire_acondicionado', models.CharField(max_length=1)),
                ('internet', models.CharField(max_length=1)),
                ('tv_cable', models.CharField(max_length=1)),
                ('estado_departamento_id_estado_departamento', models.BigIntegerField()),
                ('tarifa_id_tarifa', models.BigIntegerField(unique=True)),
                ('turismo_real_id_sucursal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDepartamento',
            fields=[
                ('id_estado_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('estado_departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_multa', models.CharField(max_length=50)),
                ('valor_multa', models.BigIntegerField()),
                ('check_out_id_check_out', models.BigIntegerField()),
            ],
            options={
                'db_table': 'multa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(max_length=50)),
                ('persona_id_persona', models.BigIntegerField()),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.BigIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('correo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nom_region', models.CharField(max_length=50)),
                ('pais_id_pais', models.BigIntegerField()),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cant_dia', models.BigIntegerField()),
                ('valor_reserva', models.BigIntegerField()),
                ('vigente', models.CharField(blank=True, max_length=1, null=True)),
                ('check_in_id_check_in', models.BigIntegerField(unique=True)),
                ('departamento_id_departamento', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_servicio', models.CharField(max_length=50)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('reserva_id_reserva', models.BigIntegerField()),
                ('tarifa_id_tarifa', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField()),
                ('departamento_id_departamento', models.BigIntegerField(unique=True)),
                ('servicio_id_servicio', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'tarifa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('usuario_id_usuario', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurismoReal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'turismo_real',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
                ('habilitado', models.CharField(max_length=1)),
                ('persona_id_persona', models.BigIntegerField()),
                ('tipo_usuario_id_tipo_usuario', models.BigIntegerField(unique=True)),
                ('turismo_real_id_sucursal', models.BigIntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
