# Generated by Django 4.1 on 2022-09-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'managed': True},
        ),
    ]
