# Generated by Django 4.1 on 2022-09-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_checkin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'managed': False},
        ),
    ]
