# Generated by Django 4.1 on 2022-09-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_checkin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TurismoReal',
        ),
    ]
