# Generated by Django 4.1 on 2022-09-17 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_turismoreal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.FloatField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=14)),
                ('nom_cliente', models.CharField(max_length=20)),
                ('apellido_paterno_cliente', models.CharField(max_length=20)),
                ('apellido_materno_cliente', models.CharField(max_length=20)),
                ('edad', models.FloatField()),
                ('nacionalidad', models.CharField(max_length=30)),
                ('email_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.FloatField()),
                ('direccion_cliente', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_fun', models.FloatField(primary_key=True, serialize=False)),
                ('rut_fun', models.CharField(max_length=14)),
                ('nombre_fun', models.CharField(max_length=20)),
                ('apellido_paterno_fun', models.CharField(max_length=20)),
                ('apellido_materno_fun', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mtto', models.FloatField(primary_key=True, serialize=False)),
                ('mtto_fecha_creacion', models.DateField()),
                ('mtto_fecha_desde', models.DateField()),
                ('mtto_fecha_hasta', models.DateField()),
                ('mtto_observacion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.OneToOneField(db_column='id_pago', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.reserva')),
                ('metodo_pago', models.CharField(max_length=20)),
                ('fecha_pago', models.DateField()),
                ('pago_efectuado', models.CharField(max_length=20)),
                ('monto_pago', models.FloatField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion_tour', models.CharField(max_length=300)),
                ('categoria_tour', models.CharField(max_length=100)),
                ('colacion_tour', models.CharField(max_length=2)),
                ('valor_tour', models.FloatField()),
            ],
            options={
                'db_table': 'tour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=14)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color_vehiculo', models.CharField(max_length=50)),
                ('cant_puerta', models.FloatField()),
                ('cant_asiento', models.FloatField()),
                ('aire_acondicionado', models.CharField(max_length=2)),
                ('id_vehiculo', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='EstadoDepartamento',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Tarifa',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterModelTable(
            name='checkin',
            table='checkin',
        ),
        migrations.AlterModelTable(
            name='checkout',
            table='checkout',
        ),
        migrations.CreateModel(
            name='Acompaniante',
            fields=[
                ('id_acompaniante', models.OneToOneField(db_column='id_acompaniante', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.cliente')),
                ('rut_acom', models.CharField(max_length=14)),
                ('nombre_acom', models.CharField(max_length=50)),
                ('apellido_acom', models.CharField(max_length=50)),
                ('edad_acom', models.FloatField()),
                ('email_acom', models.CharField(max_length=75)),
                ('telefono_acom', models.FloatField()),
            ],
            options={
                'db_table': 'acompaniante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_cond', models.OneToOneField(db_column='id_cond', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.vehiculo')),
                ('nombre_cond', models.CharField(max_length=30)),
                ('apellido_cond', models.CharField(max_length=30)),
                ('edad_cond', models.FloatField()),
                ('nacionlidad_cond', models.CharField(max_length=30)),
                ('email_cond', models.CharField(max_length=40)),
                ('telefono_cond', models.FloatField()),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicioextra',
            fields=[
                ('id_servicio', models.OneToOneField(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.conductor')),
                ('direccion_encuentro', models.CharField(max_length=75)),
                ('direccion_destino', models.CharField(max_length=75)),
                ('fecha_encuentro', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('valor_servicio', models.FloatField()),
            ],
            options={
                'db_table': 'servicioextra',
                'managed': False,
            },
        ),
    ]
